In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [11]:
merge = pd.read_csv('merged_census_and_hazards_df.csv')
hazzard = pd.read_csv('hazard_risks.csv')

In [25]:
merge[merge['county'].str.contains('City')]

,Unnamed: 0,county,state,hazard score,wildfire,tornado,landslide,hurricane,earthquake,drought,...,Estimate!!SEX AND AGE!!Total population!!21 years and over,Estimate!!SEX AND AGE!!Total population!!62 years and over,Estimate!!SEX AND AGE!!Total population!!65 years and over,Estimate!!SEX AND AGE!!Total population!!18 years and over.1,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female,Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females),Estimate!!SEX AND AGE!!Total population!!65 years and over.1,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male,Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female
699,699,Roanoke City County,VA,14,1,1,3,3,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,712,Richmond City County,VA,14,1,3,2,3,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1734,1734,James City County,VA,11,1,1,1,3,1,0,...,56357.0,21319.0,17930.0,59034.0,28138.0,30896.0,91.1,17930.0,8261.0,9669.0
2138,2138,Franklin City County,VA,11,1,3,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2219,2219,Fairfax City County,VA,11,1,3,1,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2663,2663,Charles City County,VA,11,1,2,1,3,1,0,...,5685.0,1928.0,1602.0,5896.0,2860.0,3036.0,94.2,1602.0,737.0,865.0
2705,2705,Carson City County,NV,16,3,1,1,0,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2944,2944,Bedford City County,VA,14,1,3,3,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2989,2989,Baltimore City County,MD,11,1,2,2,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
merge.shape

(3109, 105)

In [6]:
merge.i

Unnamed: 0                                                                                        0
county                                                                                            0
state                                                                                             0
hazard score                                                                                      0
wildfire                                                                                          0
                                                                                                 ..
Estimate!!SEX AND AGE!!Total population!!18 years and over!!Female                               53
Estimate!!SEX AND AGE!!Total population!!18 years and over!!Sex ratio (males per 100 females)    53
Estimate!!SEX AND AGE!!Total population!!65 years and over.1                                     53
Estimate!!SEX AND AGE!!Total population!!65 years and over!!Male                                 53
Estimate!!SEX AND AGE!!Total population!!65 years and over!!Female                               53
Length: 105, dtype: int64